---
- name: Deploy Instance HA
  hosts: controller-0
  tasks:
    - name: Copy fencing-secret.yaml
      ansible.builtin.template:
        src: templates/fencing-secret.yaml
        dest: /home/zuul/fencing-secret.yaml

    - name: Copy iha-config.yaml
      ansible.builtin.template:
        src: templates/iha-cm.yaml.j2
        dest: /home/zuul/iha-cm.yaml

    - name: Copy iha.yaml
      ansible.builtin.template:
        src: templates/iha.yaml.j2
        dest: /home/zuul/iha.yaml

    - name: Fetch redfish UUIDs and fix fencing
      ansible.builtin.shell: |
        C0=$(ssh hypervisor sudo virsh list |grep compute |awk '{print $2}' |grep '\-0$')
        C1=$(ssh hypervisor sudo virsh list |grep compute |awk '{print $2}' |grep '\-1$')

        C0N=$(echo $C0 |sed 's/cifmw-//')
        C1N=$(echo $C1 |sed 's/cifmw-//')

        UUID0=$(ssh hypervisor sudo virsh dumpxml $C0 |grep uuid |cut -d '>' -f 2 |cut -d '<' -f 1)
        UUID1=$(ssh hypervisor sudo virsh dumpxml $C1 |grep uuid |cut -d '>' -f 2 |cut -d '<' -f 1)

        sed -i "s/computeA/$C0N/g" ~/fencing-secret.yaml
        sed -i "s/computeB/$C1N/g" ~/fencing-secret.yaml

        sed -i "s/UUID0/$UUID0/g" ~/fencing-secret.yaml
        sed -i "s/UUID1/$UUID1/g" ~/fencing-secret.yaml
      changed_when: false

    - name: Deploy OCP resources
      ansible.builtin.shell: |
        oc project openstack; oc apply -f ~/fencing-secret.yaml
        oc project openstack; oc apply -f ~/iha-cm.yaml
        oc project openstack; oc apply -f ~/iha.yaml
      changed_when: false

    - name: Wait until InstanceHA pod is ready
      ansible.builtin.shell: |
        oc wait deployment/instanceha-0 -n openstack --for condition=Available --timeout=300s
      changed_when: false

    - name: Install prereq
      ansible.builtin.shell: |
        ansible-galaxy collection install openstack.cloud
        ansible-galaxy collection install community.libvirt
      changed_when: false
