---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: 08 Test Disabling flavor or image tagging
  hosts: controller-0
  gather_facts: false
  vars:
    name: "08-test-disable-flavor-or-image-tagging"
  tasks:
    - name: 08 Create results file (failure)
      ansible.builtin.template:
        src: templates/iha-tests-results.xml.j2
        dest: /home/zuul/iha-tests-results/{{ name }}.xml
      vars:
        success: false

    - name: Reset iha configmap
      ansible.builtin.template:
        src: templates/iha-cm.yaml.j2
        dest: /home/zuul/iha-cm.yaml

    - name: Apply config
      ansible.builtin.shell: |
        oc apply -f /home/zuul/iha-cm.yaml
      changed_when: false

    - name: 08 fetch random string
      ansible.builtin.shell:
        cmd: cat ~/.ssh/config |grep 'Host compute' |awk '{print $2}' |head -1|cut -d- -f2
      register: string
      changed_when: false

    - name: 08 set string as fact
      ansible.builtin.set_fact:
        string: "{{ string.stdout }}"
    - name: 08 Set compute-0 name as fact
      ansible.builtin.set_fact:
        compute0: "compute-{{ string }}-0.ctlplane.example.com"
    - name: 08 Set compute-1 name as fact
      ansible.builtin.set_fact:
        compute1: "compute-{{ string }}-1.ctlplane.example.com"
    - name: 08 Set compute-2 name as fact
      ansible.builtin.set_fact:
        compute2: "compute-{{ string }}-2.ctlplane.example.com"
    - name: 08 Create tagged flavor
      openstack.cloud.compute_flavor:
        cloud: default
        state: present
        name: iha.nanoha
        ram: 128
        vcpus: 1
        disk: 1
        extra_specs:
          hw_rng:allowed: "True"

    - name: 08 set flavor trait
      ansible.builtin.command:
        cmd: openstack --os-cloud default flavor set --property trait:CUSTOM_HA=true iha.nanoha
      changed_when: false

    - name: 08 set resource provider trait
      ansible.builtin.shell:
        cmd: |
          openstack --os-cloud default trait create CUSTOM_HA
          uuid=$(openstack --os-cloud default resource provider list -f value -c uuid |head -1)
          existing_traits=$(openstack --os-cloud default resource provider trait list -f value $uuid | sed 's/^/--trait /')
          for i in $(openstack --os-cloud default resource provider list -f value -c uuid); do openstack --os-cloud default resource provider trait set $existing_traits --trait CUSTOM_HA $i; done
      changed_when: false

    - name: 08 Create tagged image
      openstack.cloud.image:
        cloud: default
        name: cirros-ha
        container_format: bare
        disk_format: qcow2
        state: present
        filename: /home/zuul/cirros-0.6.2-iha-x86_64-disk.img
        min_disk: 0
        min_ram: 0

    - name: 08 set image trait
      ansible.builtin.command:
        cmd: openstack --os-cloud default image set --tag trait:CUSTOM_HA cirros-ha
      changed_when: false

    - name: 08 set resource provider trait
      ansible.builtin.shell:
        cmd: |
          openstack trait create CUSTOM_HA
          uuid=$(openstack --os-cloud default resource provider list -f value -c uuid |head -1)
          existing_traits=$(openstack --os-cloud default resource provider trait list -f value $uuid | sed 's/^/--trait /')
          for i in $(openstack --os-cloud default resource provider list -f value -c uuid); do openstack --os-cloud default resource provider trait set $existing_traits --trait CUSTOM_HA $i; done
      changed_when: false

    - name: 08 Create instance vm
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: present
        availability_zone: nova:{{ hostvars['controller-0']['compute0'] }}
        name: vm-flavorha
        image: cirros-0.6.2-iha-x86_64-disk.img
        timeout: 200
        flavor: iha.nanoha
        security_groups:
          - ping
        nics:
          - net-name: ihanet

    - name: 08 Create instance vm-ha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: present
        availability_zone: nova:{{ hostvars['controller-0']['compute0'] }}
        name: vm-imageha
        image: cirros-ha
        timeout: 200
        flavor: iha.nano
        security_groups:
          - ping
        nics:
          - net-name: ihanet

- name: 08 Crash compute-0
  hosts: hypervisor
  remote_user: zuul
  become: true
  gather_facts: false
  tasks:
    - name: 08 Shutdown compute
      community.libvirt.virt:
        name: cifmw-compute-{{ hostvars['controller-0']['string'] }}-0
        state: destroyed

- name: 08 Check status
  hosts: controller-0
  gather_facts: false
  vars:
    name: "08-test-disable-flavor-or-image-tagging"
  tasks:
    - name: 08 Fetch HYPERVISOR for instance vm-imageha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-imageha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor2
      retries: 60
      delay: 3
      until: hypervisor2.stdout not in hostvars['controller-0']['compute0']
      changed_when: false

    - name: 08 Fetch hypervisor for vm-imageha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-imageha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor_vmimageha
      changed_when: false

    - name: 08 Check if vm-imageha was evacuated
      ansible.builtin.fail:
        msg: '"vm-imageha not evacuated"'
      when: hypervisor_vmimageha.stdout in hostvars['controller-0']['compute0']

    - name: 08 Fetch hypervisor for instance vm-flavorha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-flavorha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor_vmflavorha
      changed_when: false

    - name: 08 Check if vm-flavorha was evacuated
      ansible.builtin.fail:
        msg: '"vm-flavorha not evacuated"'
      when: hypervisor_vmflavorha.stdout in hostvars['controller-0']['compute0']

    - name: 08 Fetch vm-flavorha status
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-flavorha |grep vm_state |tail -1  |awk '{print $4}'
      register: vmflavorha_status
      changed_when: false

    - name: 08 Check vm-flavorha status
      ansible.builtin.fail:
        msg: '"vm-flavorha should be active"'
      when: vmflavorha_status.stdout != "active"

    - name: 08 Fetch vm-imageha status
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-flavorha |grep vm_state |tail -1  |awk '{print $4}'
      register: vmimageha_status
      changed_when: false

    - name: 08 Check vm-imageha status
      ansible.builtin.fail:
        msg: '"vm-imageha should be active"'
      when: vmimageha_status.stdout != "active"

    - name: 08 Remove vm-flavorha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: vm-flavorha

    - name: 08 Remove vm-imageha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: vm-imageha

    - name: 08 Fetch compute service (hypervisor) info from OpenStack
      openstack.cloud.compute_service_info:
        cloud: default
        binary: nova-compute
      register: hypervisor_list

    - name: 08 Set fact
      ansible.builtin.set_fact:
        hypervisors: "{{ hypervisor_list.compute_services | map(attribute='host') | list | sort }}"

    - name: 08 Wait compute-0 to be up
      openstack.cloud.compute_service_info:
        cloud: default
        binary: nova-compute
        host: "{{ compute0 }}"
      register: compute_0_status
      until: "'up' in compute_0_status.compute_services | map(attribute='state')"
      retries: 6
      delay: 10

    - name: 08 save logs
      ansible.builtin.shell: oc logs deploy/instanceha-0 > /home/zuul/iha-tests-results/{{ name }}.log
      changed_when: false

    # DISABLE FLAVOR
    - name: Set tagged_flavors to false
      ansible.builtin.template:
        src: templates/iha-cm.yaml.j2
        dest: /home/zuul/iha-cm.yaml
      vars:
        tagged_flavors: "false"

    - name: Apply config
      ansible.builtin.shell: |
        oc apply -f /home/zuul/iha-cm.yaml
      changed_when: false

    - name: 08 Create instance vm-flavorha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: present
        availability_zone: nova:{{ hostvars['controller-0']['compute0'] }}
        name: vm-flavorha
        image: cirros-0.6.2-iha-x86_64-disk.img
        timeout: 200
        flavor: iha.nanoha
        security_groups:
          - ping
        nics:
          - net-name: ihanet

    - name: 08 Create instance vm-imageha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: present
        availability_zone: nova:{{ hostvars['controller-0']['compute0'] }}
        name: vm-imageha
        image: cirros-ha
        timeout: 200
        flavor: iha.nano
        security_groups:
          - ping
        nics:
          - net-name: ihanet

- name: 08 Crash compute-0
  hosts: hypervisor
  remote_user: zuul
  become: true
  gather_facts: false
  tasks:
    - name: 08 Shutdown compute
      community.libvirt.virt:
        name: cifmw-compute-{{ hostvars['controller-0']['string'] }}-0
        state: destroyed

- name: 08 Check status
  hosts: controller-0
  gather_facts: false
  vars:
    name: "08-test-disable-flavor-or-image-tagging"
  tasks:
    - name: 08 Fetch HYPERVISOR for instance vm-imageha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-imageha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor2
      retries: 60
      delay: 3
      until: hypervisor2.stdout not in hostvars['controller-0']['compute0']
      changed_when: false

    - name: 08 Fetch hypervisor for vm-imageha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-imageha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor_vmimageha
      changed_when: false

    - name: 08 Check if vm-imageha was evacuated
      ansible.builtin.fail:
        msg: '"vm-imageha not evacuated"'
      when: hypervisor_vmimageha.stdout in hostvars['controller-0']['compute0']

    - name: 08 Fetch hypervisor for instance vm-flavorha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-flavorha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor_vmflavorha
      changed_when: false

    - name: 08 Check if vm-flavorha was evacuated
      ansible.builtin.fail:
        msg: '"vm-flavorha evacuated"'
      when: hypervisor_vmflavorha.stdout not in hostvars['controller-0']['compute0']

    - name: 08 Fetch vm-flavorha status
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-flavorha |grep vm_state |tail -1  |awk '{print $4}'
      register: vmflavorha_status
      changed_when: false

    - name: 08 Fetch vm-imageha status
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-imageha |grep vm_state |tail -1  |awk '{print $4}'
      register: vmimageha_status
      changed_when: false

    - name: 08 Check vm-imageha status
      ansible.builtin.fail:
        msg: '"vm-imageha should be active"'
      when: vmimageha_status.stdout != "active"

    - name: 08 Remove vm-flavorha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: vm-flavorha

    - name: 08 Remove vm-imageha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: vm-imageha

    - name: 08 Fetch compute service (hypervisor) info from OpenStack
      openstack.cloud.compute_service_info:
        cloud: default
        binary: nova-compute
      register: hypervisor_list

    - name: 08 Set fact
      ansible.builtin.set_fact:
        hypervisors: "{{ hypervisor_list.compute_services | map(attribute='host') | list | sort }}"

    - name: 08 Wait compute-0 to be up
      openstack.cloud.compute_service_info:
        cloud: default
        binary: nova-compute
        host: "{{ compute0 }}"
      register: compute_0_status
      until: "'up' in compute_0_status.compute_services | map(attribute='state')"
      retries: 6
      delay: 10

    - name: 08 save logs
      ansible.builtin.shell: oc logs deploy/instanceha-0 >> /home/zuul/iha-tests-results/{{ name }}.log
      changed_when: false

    - name: Reset iha configmap
      ansible.builtin.template:
        src: templates/iha-cm.yaml.j2
        dest: /home/zuul/iha-cm.yaml

    - name: Apply config
      ansible.builtin.shell: |
        oc apply -f /home/zuul/iha-cm.yaml
      changed_when: false

    # DISABLE IMAGE
    - name: Set tagged_images to false
      ansible.builtin.template:
        src: templates/iha-cm.yaml.j2
        dest: /home/zuul/iha-cm.yaml
      vars:
        tagged_images: "false"

    - name: Apply config
      ansible.builtin.shell: |
        oc apply -f /home/zuul/iha-cm.yaml
      changed_when: false

    - name: 08 Create instance vm
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: present
        availability_zone: nova:{{ hostvars['controller-0']['compute0'] }}
        name: vm-flavorha
        image: cirros-0.6.2-iha-x86_64-disk.img
        timeout: 200
        flavor: iha.nanoha
        security_groups:
          - ping
        nics:
          - net-name: ihanet

    - name: 08 Create instance vm-ha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: present
        availability_zone: nova:{{ hostvars['controller-0']['compute0'] }}
        name: vm-imageha
        image: cirros-ha
        timeout: 200
        flavor: iha.nano
        security_groups:
          - ping
        nics:
          - net-name: ihanet

- name: 08 Crash compute-0
  hosts: hypervisor
  remote_user: zuul
  become: true
  gather_facts: false
  tasks:
    - name: 08 Shutdown compute
      community.libvirt.virt:
        name: cifmw-compute-{{ hostvars['controller-0']['string'] }}-0
        state: destroyed

- name: 08 Check status
  hosts: controller-0
  gather_facts: false
  vars:
    name: "08-test-disable-flavor-or-image-tagging"
  tasks:
    - name: 08 Fetch HYPERVISOR for instance vm-flavorha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-flavorha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor2
      retries: 60
      delay: 3
      until: hypervisor2.stdout not in hostvars['controller-0']['compute0']
      changed_when: false

    - name: 08 Fetch hypervisor for vm-imageha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-imageha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor_vmimageha
      changed_when: false

    - name: 08 Check if vm-imageha was evacuated
      ansible.builtin.fail:
        msg: '"vm-imageha evacuated"'
      when: hypervisor_vmimageha.stdout not in hostvars['controller-0']['compute0']

    - name: 08 Fetch hypervisor for instance vm-flavorha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-flavorha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor_vmflavorha
      changed_when: false

    - name: 08 Check if vm-flavorha was evacuated
      ansible.builtin.fail:
        msg: '"vm-flavorha not evacuated"'
      when: hypervisor_vmflavorha.stdout in hostvars['controller-0']['compute0']

    - name: 08 Fetch vm-flavorha status
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-flavorha |grep vm_state |tail -1  |awk '{print $4}'
      register: vmflavorha_status
      changed_when: false

    - name: 08 Check vm-flavorha status
      ansible.builtin.fail:
        msg: '"vm-flavorha should be active"'
      when: vmflavorha_status.stdout != "active"

    - name: 08 Fetch vm-imageha status
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-imageha |grep vm_state |tail -1  |awk '{print $4}'
      register: vmimageha_status
      changed_when: false

    - name: 08 Remove vm-flavorha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: vm-flavorha

    - name: 08 Remove vm-imageha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: vm-imageha

    - name: 08 Fetch compute service (hypervisor) info from OpenStack
      openstack.cloud.compute_service_info:
        cloud: default
        binary: nova-compute
      register: hypervisor_list

    - name: 08 Set fact
      ansible.builtin.set_fact:
        hypervisors: "{{ hypervisor_list.compute_services | map(attribute='host') | list | sort }}"

    - name: 08 Wait compute-0 to be up
      openstack.cloud.compute_service_info:
        cloud: default
        binary: nova-compute
        host: "{{ compute0 }}"
      register: compute_0_status
      until: "'up' in compute_0_status.compute_services | map(attribute='state')"
      retries: 60
      delay: 10

    - name: 08 save logs
      ansible.builtin.shell: oc logs deploy/instanceha-0 >> /home/zuul/iha-tests-results/{{ name }}.log
      changed_when: false

    - name: Reset iha configmap
      ansible.builtin.template:
        src: templates/iha-cm.yaml.j2
        dest: /home/zuul/iha-cm.yaml

    - name: Apply config
      ansible.builtin.shell: |
        oc apply -f /home/zuul/iha-cm.yaml
      changed_when: false

    - name: 08 Remove tagged image
      openstack.cloud.image:
        cloud: default
        state: absent
        name: cirros-ha

    - name: 08 Remove tagged flavor
      openstack.cloud.compute_flavor:
        cloud: default
        state: absent
        name: iha.nanoha

    - name: 08 Create results file (success)
      ansible.builtin.template:
        src: templates/iha-tests-results.xml.j2
        dest: /home/zuul/iha-tests-results/{{ name }}.xml
      vars:
        success: true
